version: 0.0
Resources:
  - myECSService:
      Type: AWS::ECS::Service
      Properties:
        ClusterName: spring-boot-app  # Your ECS cluster name
        ServiceName: blue-green  # Your ECS service name
        TaskDefinition: imagedefinitions:11  # ECS task definition with the revision number
        LoadBalancerInfo:
          ContainerName: spring-app  # Container name as defined in the task definition
          ContainerPort: 80  # The container port exposed
