version: 0.0
Resources:
  - myECSService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: imagedefinitions:12  # ECS task definition with the revision number
        LoadBalancerInfo:
          ContainerName: spring-app  # Container name as defined in the task definition
          ContainerPort: 80  # The container port exposed
