version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskdef.json"  # Reference to the task definition file
        LoadBalancerInfo:
          ContainerName: "spring-app"   # Must match your taskdef.json container name
          ContainerPort: 80             # Must match the exposed port in your Dockerfile
