version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing jq...
      - yum install -y jq
      - echo Installing Maven...
      - yum install -y maven
      - echo Building the JAR file...
