version: 0.2

phases:
  pre_build:
    commands:
    - echo Installing dependencies...
    - yum install -y jq maven
    - echo Logging in to Amazon ECR...
    - aws --version
    - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 897729119076.dkr.ecr.us-east-1.amazonaws.com
    - REPOSITORY_URI=897729119076.dkr.ecr.us-east-1.amazonaws.com/spring-app
    - IMAGE_TAG=latest
    - echo Building the JAR file...
    - mvn clean install
  build:
    commands:
    - echo Building the Docker image...
    - docker build -t $REPOSITORY_URI:$IMAGE_TAG --platform linux/amd64 .
  post_build:
    commands:
    - echo Pushing Docker image to ECR...
    - docker push $REPOSITORY_URI:$IMAGE_TAG
    - echo Writing imagedefinitions.json for ECS...
    - printf '[{"name":"spring-app","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
    - echo Writing appspec.yml...
    - cat imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json
  - appspec.yml
